name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  DATABASE_URL: "postgres://postgres:secret@localhost:5432"
  REDIS_URL: "redis://127.0.0.1:6379/0"
  GOOGLE_CLIENT_ID: "123"
  GOOGLE_CLIENT_SECRET: "123"
  NEXTAUTH_SECRET: "secret"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXT_PUBLIC_WS_SERVER: "ws://localhost:4444"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  build:
    name: Build and Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Run Postgres and Redis
        run: docker-compose up -d

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Push Database Schema
        run: npx turbo run db:push

      - name: Start and Test
        run: npm run start &
          sleep 5 &&
          curl http://localhost:3000 -I &&
          npm run test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
